/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

var util = require('util');

/**
 * @class
 * Initializes a new instance of the FloorViewModel class.
 * @constructor
 * @member {number} [id]
 * 
 * @member {number} [locationId]
 * 
 * @member {string} [name]
 * 
 * @member {array} [facilities]
 * 
 * @member {date} [created]
 * 
 * @member {date} [modified]
 * 
 */
function FloorViewModel() {
}

/**
 * Defines the metadata of FloorViewModel
 *
 * @returns {object} metadata of FloorViewModel
 *
 */
FloorViewModel.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'FloorViewModel',
    type: {
      name: 'Composite',
      className: 'FloorViewModel',
      modelProperties: {
        id: {
          required: false,
          serializedName: 'id',
          type: {
            name: 'Number'
          }
        },
        locationId: {
          required: false,
          serializedName: 'locationId',
          type: {
            name: 'Number'
          }
        },
        name: {
          required: false,
          serializedName: 'name',
          type: {
            name: 'String'
          }
        },
        facilities: {
          required: false,
          serializedName: 'facilities',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'FacilityViewModelElementType',
                type: {
                  name: 'Composite',
                  className: 'FacilityViewModel'
                }
            }
          }
        },
        created: {
          required: false,
          serializedName: 'created',
          type: {
            name: 'DateTime'
          }
        },
        modified: {
          required: false,
          serializedName: 'modified',
          type: {
            name: 'DateTime'
          }
        }
      }
    }
  };
};

module.exports = FloorViewModel;
