/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


/**
 * @class
 * Initializes a new instance of the FloorViewModel class.
 * @constructor
 * @member {number} [id]
 * 
 * @member {number} [locationId]
 * 
 * @member {string} [name]
 * 
 * @member {array} [facilities]
 * 
 * @member {date} [created]
 * 
 * @member {date} [modified]
 * 
 */
export interface FloorViewModel {
    id?: number;
    locationId?: number;
    name?: string;
    facilities?: FacilityViewModel[];
    created?: Date;
    modified?: Date;
}

/**
 * @class
 * Initializes a new instance of the FacilityViewModel class.
 * @constructor
 * @member {number} [id]
 * 
 * @member {string} [name]
 * 
 * @member {string} [value]
 * 
 * @member {date} [created]
 * 
 * @member {date} [modified]
 * 
 */
export interface FacilityViewModel {
    id?: number;
    name?: string;
    value?: string;
    created?: Date;
    modified?: Date;
}

/**
 * @class
 * Initializes a new instance of the LocationViewModel class.
 * @constructor
 * @member {number} [id]
 * 
 * @member {string} [name]
 * 
 * @member {string} [address]
 * 
 * @member {string} [postcode]
 * 
 * @member {string} [city]
 * 
 * @member {string} [phonenumber]
 * 
 * @member {string} [openingHours]
 * 
 * @member {number} [latitude]
 * 
 * @member {number} [longitude]
 * 
 * @member {array} [facilities]
 * 
 * @member {date} [created]
 * 
 * @member {date} [modified]
 * 
 */
export interface LocationViewModel {
    id?: number;
    name?: string;
    address?: string;
    postcode?: string;
    city?: string;
    phonenumber?: string;
    openingHours?: string;
    latitude?: number;
    longitude?: number;
    facilities?: FacilityViewModel[];
    created?: Date;
    modified?: Date;
}

/**
 * @class
 * Initializes a new instance of the NotificationViewModel class.
 * @constructor
 * @member {boolean} [claimed]
 * 
 */
export interface NotificationViewModel {
    claimed?: boolean;
}

/**
 * @class
 * Initializes a new instance of the WorkspaceViewModel class.
 * @constructor
 * @member {number} [id]
 * 
 * @member {number} [floorId]
 * 
 * @member {string} [name]
 * 
 * @member {boolean} [claimed]
 * 
 * @member {date} [claimedUntill]
 * 
 * @member {array} [facilities]
 * 
 * @member {date} [created]
 * 
 * @member {date} [modified]
 * 
 */
export interface WorkspaceViewModel {
    id?: number;
    floorId?: number;
    name?: string;
    claimed?: boolean;
    claimedUntill?: Date;
    facilities?: FacilityViewModel[];
    created?: Date;
    modified?: Date;
}

/**
 * @class
 * Initializes a new instance of the StatusViewModel class.
 * @constructor
 * @member {boolean} [claimed]
 * 
 * @member {date} [claimedUntill]
 * 
 */
export interface StatusViewModel {
    claimed?: boolean;
    claimedUntill?: Date;
}
