/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.FloorViewModel = require('./floorViewModel');
exports.FacilityViewModel = require('./facilityViewModel');
exports.LocationViewModel = require('./locationViewModel');
exports.NotificationViewModel = require('./notificationViewModel');
exports.WorkspaceViewModel = require('./workspaceViewModel');
exports.StatusViewModel = require('./statusViewModel');
