/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

var util = require('util');

/**
 * @class
 * Initializes a new instance of the LocationViewModel class.
 * @constructor
 * @member {number} [id]
 * 
 * @member {string} [name]
 * 
 * @member {string} [address]
 * 
 * @member {string} [postcode]
 * 
 * @member {string} [city]
 * 
 * @member {string} [phonenumber]
 * 
 * @member {string} [openingHours]
 * 
 * @member {number} [latitude]
 * 
 * @member {number} [longitude]
 * 
 * @member {array} [facilities]
 * 
 * @member {date} [created]
 * 
 * @member {date} [modified]
 * 
 */
function LocationViewModel() {
}

/**
 * Defines the metadata of LocationViewModel
 *
 * @returns {object} metadata of LocationViewModel
 *
 */
LocationViewModel.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'LocationViewModel',
    type: {
      name: 'Composite',
      className: 'LocationViewModel',
      modelProperties: {
        id: {
          required: false,
          serializedName: 'id',
          type: {
            name: 'Number'
          }
        },
        name: {
          required: false,
          serializedName: 'name',
          type: {
            name: 'String'
          }
        },
        address: {
          required: false,
          serializedName: 'address',
          type: {
            name: 'String'
          }
        },
        postcode: {
          required: false,
          serializedName: 'postcode',
          type: {
            name: 'String'
          }
        },
        city: {
          required: false,
          serializedName: 'city',
          type: {
            name: 'String'
          }
        },
        phonenumber: {
          required: false,
          serializedName: 'phonenumber',
          type: {
            name: 'String'
          }
        },
        openingHours: {
          required: false,
          serializedName: 'openingHours',
          type: {
            name: 'String'
          }
        },
        latitude: {
          required: false,
          serializedName: 'latitude',
          type: {
            name: 'Number'
          }
        },
        longitude: {
          required: false,
          serializedName: 'longitude',
          type: {
            name: 'Number'
          }
        },
        facilities: {
          required: false,
          serializedName: 'facilities',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'FacilityViewModelElementType',
                type: {
                  name: 'Composite',
                  className: 'FacilityViewModel'
                }
            }
          }
        },
        created: {
          required: false,
          serializedName: 'created',
          type: {
            name: 'DateTime'
          }
        },
        modified: {
          required: false,
          serializedName: 'modified',
          type: {
            name: 'DateTime'
          }
        }
      }
    }
  };
};

module.exports = LocationViewModel;
