/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the NotificationViewModel class.
 * @constructor
 * @member {boolean} [claimed]
 * 
 */
function NotificationViewModel() {
}

/**
 * Defines the metadata of NotificationViewModel
 *
 * @returns {object} metadata of NotificationViewModel
 *
 */
NotificationViewModel.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'NotificationViewModel',
    type: {
      name: 'Composite',
      className: 'NotificationViewModel',
      modelProperties: {
        claimed: {
          required: false,
          serializedName: 'claimed',
          type: {
            name: 'Boolean'
          }
        }
      }
    }
  };
};

module.exports = NotificationViewModel;
