/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the StatusViewModel class.
 * @constructor
 * @member {boolean} [claimed]
 * 
 * @member {date} [claimedUntill]
 * 
 */
function StatusViewModel() {
}

/**
 * Defines the metadata of StatusViewModel
 *
 * @returns {object} metadata of StatusViewModel
 *
 */
StatusViewModel.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'StatusViewModel',
    type: {
      name: 'Composite',
      className: 'StatusViewModel',
      modelProperties: {
        claimed: {
          required: false,
          serializedName: 'claimed',
          type: {
            name: 'Boolean'
          }
        },
        claimedUntill: {
          required: false,
          serializedName: 'claimedUntill',
          type: {
            name: 'DateTime'
          }
        }
      }
    }
  };
};

module.exports = StatusViewModel;
